//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinformsDUCCompany1a
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Employee
    {
        public int EmpId { get; set; }
        public string EmpName { get; set; }
        public System.DateTime EmpDOB { get; set; }
        public string EmpGender { get; set; }
        public string EmpImagePath { get; set; }
        public string EmpAddress { get; set; }
        public int DepartmentId { get; set; }
        public int PositionId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Position Position { get; set; }
    }
}
